# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/CSL/AN 3 - SEM 1/ssc lab/project_3/project_3.cache/wt} [current_project]
set_property parent.project_path {D:/CSL/AN 3 - SEM 1/ssc lab/project_3/project_3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/CSL/AN 3 - SEM 1/ssc lab/project_3/project_3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{D:/CSL/AN 3 - SEM 1/ssc lab/project_3/project_3.srcs/sources_1/new/divider.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top divider -part xc7k70tfbv676-1


write_checkpoint -force -noxdef divider.dcp

catch { report_utilization -file divider_utilization_synth.rpt -pb divider_utilization_synth.pb }
